export const SET_USER_ROLE = ' SET_USER_ROLE'
export const IS_SIDE_BAR_OPEN = 'IS_SIDE_BAR_OPEN'
export const IS_SIDE_BAR_CHILDLIST_OPEN = 'IS_SIDE_BAR_CHILDLIST_OPEN'
export const SET_SIDEBAR_ITEM_CURRENT_ACTIVED_ID = 'SET_SIDEBAR_ITEM_CURRENT_ACTIVED_ID'
